### ISSUE TITLE
chore: github action  수정

### ISSUE THREAD

**Issue by newkayak12** [newkayak12/prototype-reservation-system#22]
### 📄 설명

- todo-to-isseue
- autoclosable-issue

권한 부족 

### ✅ 작업할 내용

```yaml
permissions:
    issues: write
    pull-requests: write

```
